apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eodt-api-ingress
  namespace: eodt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: icg-cpd-cluster.port.ac.uk
      http:
        paths:
          - path: /eodt(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eodt-api-service
                port:
                  number: 80
