---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: eodt
spec:
  encryptedData:
    .dockerconfigjson: AgA3LdKKlCxMBsyUtjwor9gRDXoKMlVxXXCvRHyuKmDVCEX8+a7NxOO4wi3RzDOaiaRUuE8CRJya4+bMS3QDjpgAtDf2zp3ENDVYNCQ9pOcigjesT8iJ2NhHVEIOWZPGhjdHrj7oCtjq84fGvixqPeI6/oxyKUYIB6ErZjFrdbzEpmPo5ExIiZndItp7Q456aZAkUOvvVkuaIsh2RXZjDayg8zaPWmjnjhYsl2WXR4FQ4Nc5c61F36SsDFzG++JW4y4yNnAFvNl7OY+1nmzuvsKdWHG1wcsGMNec7qgqXvZwco0uM1G98NSXLKitKDJP4CynhepTGMb/3Sgz9lo8AND+WP5b9EIEM2WeMOHk2ttKkLTvTenp5dCME/YQMPd5E8D29KnPa6UHlbWNNv6WwibHlKkRE1l7FnQr2FzA36ZFYDYIOGTpH5Sqjjg4xJbJcVAhT6dcV9JmAMivehOdta6xdvnZ0JFoEt1SUGW3vLhdjUkPRJjTfdfPmNAKFwnAJQzgDdnUMqMYigGKWmk7ohlpzm/QqDiOHUL8C3ZkOk5PICf5O6wvTB/7obdANPl9g4CqjgOKUGUhZ8C1qE90O/5ZPVf7BRyrMsdpBm4awwDX8HtB0+oP3WuAW944O8Lzcqv5FwN7FPoWbqXis/t3ihnjUG+714PWa2R6qs4VQ1OBr7SxkezVhUXbYh5I1z4A7cGB1oguN+7gkL6MLn4lofHovm2bDNEwJSGw3S+YNNXRHgVOAEJ9doM5eBtHCtBwGe0pju7QitkNhUnN8aH4KgaooBCj21rDwwiOASexoIGzpr2l7sOWJVFkSCt76yB7672gAVbhLOmX+9JTYI7vggV0VjVkfL2BslW+VS8/lnNmxjCncwe+j1FOWRj+zxVx2QhKvvwT64O7/sVLLALn7Q9vV+vs1S8zQt2g8vDdfNWe0XGHhSKLH2cySMKnFuPBMkbIejXLg3Sy/jGFilYNpAKESYrkTA/RgPMRYyJg+iJb
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: eodt
    type: kubernetes.io/dockerconfigjson
