---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: eodt
  namespace: flux-system
spec:
  image: ghcr.io/arthurtolley/eodt
  interval: 1m0s
  secretRef:
    name: ghcr-pull-secret
