apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eodt
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/prod-cluster/eodt
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: eodt
  dependsOn:
    - name: flux-system
  wait: true
  timeout: 2m
