---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAOJr33AhtZEihvL3/poD9k7hJXxHHyQM3IXowjZpQ7hMK2W5PReeFb7B++Efg/NiYy8/I9pahtphtFrYkQ1obIphF4+InDESuYLmDjL31iRz0JHhOAkyLDhp14n4q6CtbWykQ5eRq+SLRrigbsCpcpbWFrCBQnTa5a74Qg1LcN9rJ2Uy8RahbtR47jk4ylbWqCyLUgsxraUIlhF7wlA2f7M3sGCBvwYSqxOAnjGWN2t+kPTDC6XJt9I1bY08m4lk64uNkxrf3HlfPbwx8aEaOjXXy3j9TZ3TxhLXlEUiw7LxxOfc/VE+jw9MfLScCBTW92kRThgz8T3asmpHO0NwjGky66qXWXuRC8lyo08ugs8HEIHRQg8mIlovnHFRuo/7qEGoxqbGRJ9DmFd1/lK9hxE+7v5aL1LUYR9K4ykiorGU+GjMln6IEW7bJVdFDZZVK5Xn+ubAc0yxxPJ6shm/0PX6edNW7kGaFUMohLNZumchLCSsU4gDo+EHk4pPj7ci5mWt7HG49yILw8zIBldpbGvTxejgbn51UtPpFOrecI8xdLCter9h1grDtwko9Qv2tMpkPiRWNwCE1cWYTlo9MlRmOAJtiwcedVkUr/KRf3b0GVcyLAKDl4Vjc+Y4x2ZEdwcB2ewGKokp7e3a1BNrqAS7gqiLf+1L61O5jbhXL9EQg6QqiAxDpulMQqFjZTSr5sEp8EXoAAVGzOnUQ/sYBV+eS7cLvJIqQiAkXDJF8tphYC7BrIyxFSn8GPU7t+ZRFKB4P3xp9AFuOSuXrOwRTud/TWgc3yA0Ac72kv+9SRbBjr7vXzRtT3pYS3YEy99/Ii4WPKa9dRGPGnylv3C7Oq6WLW31Arw0+sF0NObZfcIeetYhs/bB2srlUjCP/zMRAH1pEcSvBiYfzSAypv9/Zhv2tH48vfZDJXIVkTMBYYAu9OaMKaW21f9aaq1eRyj0ZJ+kykxfgttNU9LSoCTWBJMHr8bWfH8oOUpFubUeEC
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
